services:
  jupyter-spark:
    image: my_pyspark_image:latest

    # build:
    #   context: .
    #   dockerfile: Dockerfile

    ports:
      - "4040:4040"
      - "8888:8888"

    volumes:
      - .:/workspace
      - pyspark_pip_cache:/usr/local/lib/python3.12/site-packages

    working_dir: /workspace

    environment:
      - JUPYTER_ENABLE_LAB=yes

    # deploy:
    #   resources:
    #     limits:
    #       cpus: "6.0"
    #       memory: 12G

volumes:
  pyspark_pip_cache:
    external: true
